---
galaxy_info:
  author: ansible-home-cluster
  description: Common utilities/packages for hosts in the cluster.
  license: MIT
  min_ansible_version: '2.13'
  platforms:
    - name: GenericLinux
      versions: ['all']
dependencies: []
