---
galaxy_info:
  author: ansible-home-cluster
  description: Base OS setup (locale, hostname, timezone, hosts, groups).
  license: MIT
  min_ansible_version: '2.13'
  platforms:
    - name: GenericLinux
      versions: ['all']
dependencies:
  - role: facts
    when: facts_was_executed is not defined
