---
galaxy_info:
  author: ansible-home-cluster
  description: Deploy and configure Pi-hole in Docker.
  license: MIT
  min_ansible_version: '2.13'
  platforms:
    - name: GenericLinux
      versions: ['all']
dependencies:
  - role: utils
    when: utils_was_executed is not defined
  - role: docker
    when: docker_was_executed is not defined
