---
- name: Ping all devices and execute facts role
  hosts: all
  gather_facts: true
  vars:
    ansible_ssh_timeout: 10
  gather_timeout: 10
  strategy: free

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Execute facts role
      import_role:
        name: facts
